### ISSUE TITLE
Error while iterating Users data using PageIterator

### ISSUE THREAD

**Issue by caturandi-labs** [microsoftgraph/msgraph-sdk-go-core#166]
GO Version: 1.20

SDK version

```
require (
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.2.1
	github.com/joho/godotenv v1.5.1
	github.com/microsoftgraph/msgraph-sdk-go v0.56.0
	github.com/microsoftgraph/msgraph-sdk-go-core v0.34.0
)

```

Error:

```
panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 1 [running]:
reflect.Value.IsNil(...)
	/usr/local/opt/go/libexec/src/reflect/value.go:1556
github.com/microsoftgraph/msgraph-sdk-go-core.convertToPage({0x1d10f20, 0xc0004de720})
	/Users/caturandip/golang-apps/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.34.0/page_iterator.go:205 +0x4e5
github.com/microsoftgraph/msgraph-sdk-go-core.NewPageIterator({0x1d10f20?, 0xc0004de720?}, {0x1ef7b90, 0xc000142be0}, 0x1e20ff0)
	/Users/caturandip/golang-apps/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.34.0/page_iterator.go:55 +0x49
main.main()
	/Users/caturandip/golang-apps/gographapi/main.go:51 +0x389
exit status 2
```

Line code trigger error:

```
// Use PageIterator to iterate through all users
	pageIterator, err := msgraphgocore.NewPageIterator(result, client.GetAdapter(), models.CreateUserCollectionResponseFromDiscriminatorValue)

	if err != nil {
		log.Fatalln("Error in Iterator ", err.Error())
	}

	err = pageIterator.Iterate(context.Background(), func(pageItem interface{}) bool {
		user := pageItem.(models.Userable)
		fmt.Printf("%s\n", *user.GetDisplayName())
		return true
	})
```

the error happens after successfully authentication

Please help

**Comment by rkodev** [comment]
Hi @caturandi-labs, this can be achieved by logging all the request that are sent via `http.Client`, you can use a number of different methods available such as tracing using `https://go.dev/blog/http-tracing` or a number of libraries out there that are present to log the http request.

1. You will need to provide an implementation of the `http.Client` that has logging 
2. Provide this to the request adapter i.e 

For example using the http.Client to implement [this](https://go.dev/blog/http-tracing) tracing

```go
         t := &transport{}

        req, _ := http.NewRequest("GET", "https://google.com", nil)
        trace := &httptrace.ClientTrace{
            GotConn: t.GotConn,
        }

	httpClient := &http.Client{
		Transport: t,
	}
	adapter, err := msgraphsdk.NewGraphRequestAdapterWithParseNodeFactoryAndSerializationWriterFactoryAndHttpClient(auth, nil, nil, httpClient)

// get the client 
client := msgraphsdk.NewGraphServiceClient(adapter)

```

**Comment by rkodev** [comment]
A simple alternative, you can use a log library to simply provide a traced transport object

**Comment by caturandi-labs** [comment]
is it released already? or waiting for v0.34.1 ? try using 0.34.1 but got error  @rkodev

**Comment by rkodev** [comment]
Hi @caturandi-labs it should be released, please upgrade the dependency

**Comment by caturandi-labs** [comment]
@rkodev , the result when i run ` go list -u -m all`

```
not found: github.com/microsoftgraph/msgraph-sdk-go-core@v0.34.1: invalid version: unknown revision v0.34.1
```

any clue ?

**Comment by caturandi-labs** [comment]
SOLVED ! THANKS ALL
