### ISSUE TITLE
PageIterator results in reflect.Value.IsNil on zero Value

### ISSUE THREAD

**Issue by philipf** [microsoftgraph/msgraph-sdk-go-core#222]
Version: `github.com/microsoftgraph/msgraph-sdk-go-core v1.0.0`

## Error
I receive the following error when iterating to an item that exceeds the specified page size

```go
panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 1 [running]:
reflect.Value.IsNil({0x0?, 0x0?, 0xc00015ccd0?})
        /usr/local/go/src/reflect/value.go:1568 +0xbf
github.com/microsoftgraph/msgraph-sdk-go-core.convertToPage[...]({0x1307ea0, 0xc0002c9890})
        /go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v1.0.0/page_iterator.go:219 +0xf8
github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator[...]).next(0x148f520?, {0x148b540, 0x20baba0?})
        /go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v1.0.0/page_iterator.go:136 +0x91
github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator[...]).Iterate(0x148f520, {0x148b540, 0x20baba0}, 0xc00015ccd0)
        /go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v1.0.0/page_iterator.go:96 +0xc8
```

![image](https://github.com/microsoftgraph/msgraph-sdk-go-core/assets/45515/021b66c9-e56e-433c-be55-6680c10b6737)

## Code
I have based my implementation of the [iteration document of the SDK](https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=go#iterate-over-all-the-messages)
The code causes this issue when the next page is being fetched.

```go
var graphClient = graphHelper.userClient
lists, err := graphClient.Me().Todo().Lists().Get(context.Background(), nil)

if err != nil {
	fmt.Printf("Error creating lists: %v\n", err)
}

for _, list := range lists.GetValue() {
	headers := abstractions.NewRequestHeaders()

	var pageSize int32 = 5
	query := users.ItemTodoListsItemTasksRequestBuilderGetQueryParameters{
		Top: &pageSize,
	}

	options := users.ItemTodoListsItemTasksRequestBuilderGetRequestConfiguration{
		Headers:         headers,
		QueryParameters: &query,
	}

	listId := *list.GetId()
	tasks, err := graphClient.Me().Todo().Lists().ByTodoTaskListIdString(listId).Tasks().Get(context.Background(), &options)

	if err != nil {
		log.Fatalf("Error ByTodoTaskListIdString: %v\n", err)
	}

	pageIterator, err := graphcore.NewPageIterator[*models.TodoTask](
		tasks,
		graphClient.GetAdapter(),
		models.CreateTodoTaskFromDiscriminatorValue)

	if err != nil {
		log.Fatalf("Error creating page iterator: %v\n", err)
	}

	pageIterator.SetHeaders(headers)

	err = pageIterator.Iterate(
		context.Background(),
		func(task *models.TodoTask) bool {
			fmt.Printf("Task: %s\n", *task.GetTitle())
			return true
		})

	if err != nil {
		log.Fatalf("Error iterating over messages: %v\n", err)
	}
}
```

## References
Possibly related to these previously logged issues
- https://github.com/microsoftgraph/msgraph-sdk-go/issues/433
- https://github.com/microsoftgraph/msgraph-sdk-go/issues/558

**Comment by philipf** [comment]
It turns out that my code creating the PageIterator was incorrect and should be using `CreateTodoTaskCollectionResponseFromDiscriminatorValue` instead:

```go
	pageIterator, err := graphcore.NewPageIterator[*models.TodoTask](
		tasks,
		graphClient.GetAdapter(),
		models.CreateTodoTaskCollectionResponseFromDiscriminatorValue)
```

I don't know if it is possible, but it would make the API easier to use and less error-prone to use if the parser factory can be inferred from the model type.
